# Generated by Django 5.2 on 2025-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
